parameters:
  - name: containerRegistry
    displayName: Container registry name
    type: string
    default: acr-eitweueitwhlacr
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "apps/beta-distribution/*"
    exclude:
      - "**/*.md"
      - "**/*.bash"

pool:
  vmImage: "ubuntu-latest"

variables:
  projectName: "beta-distribution"
  version.major: "1"
  version.minor: "0"
  version.majorMinor: ${{ format('{0}.{1}', variables['version.major'], variables['version.minor']) }}
  version.patch: $[counter(variables['version.majorMinor'], 0)]
  version.build: $[counter(variables['projectName'], 0)]
  version.release: $(version.major).$(version.minor).$(version.patch)
  version.dev: $(version.major).$(version.minor).$(version.patch)-dev.$(Build.BuildId)
  ${{ if eq( variables['Build.SourceBranchName'], 'main' ) }}:
    versionTag: $(version.release)
    publishTags: $(versionTag),latest
  ${{ else }}:
    versionTag: $(version.dev)
    publishTags: $(versionTag)

jobs:
  - job: build
    displayName: Build docker images
    steps:
      - template: ../../.azuredevops/build-and-push.yaml
        parameters:
          displayName: "Beta distribution"
          containerRegistry: ${{ parameters.containerRegistry }}
          dockerfile: "apps/beta-distribution/Dockerfile"
          dockerContext: apps/beta-distribution
          dockerArguments: "--platform linux/arm64"
          imageName:  external/beta-distribution
          versionTag: $(versionTag)
          tags: $(publishTags)
